/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'ProxyAdmin', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ProxyAdmin__factory>
getContractFactory(name: 'ITransparentUpgradeableProxy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.ITransparentUpgradeableProxy__factory>
getContractFactory(name: 'TransparentUpgradeableProxy', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.TransparentUpgradeableProxy__factory>
getContractFactory(name: 'MetaERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MetaERC20__factory>
getContractFactory(name: 'MetaNFT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MetaNFT__factory>
getContractFactory(name: 'MetaNFTAuction', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MetaNFTAuction__factory>
getContractFactory(name: 'MetaNFTAuctionV2', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MetaNFTAuctionV2__factory>
getContractFactory(name: 'MetaOracle', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MetaOracle__factory>

  getContractAt(name: 'ProxyAdmin', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ProxyAdmin>
getContractAt(name: 'ITransparentUpgradeableProxy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.ITransparentUpgradeableProxy>
getContractAt(name: 'TransparentUpgradeableProxy', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.TransparentUpgradeableProxy>
getContractAt(name: 'MetaERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MetaERC20>
getContractAt(name: 'MetaNFT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MetaNFT>
getContractAt(name: 'MetaNFTAuction', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MetaNFTAuction>
getContractAt(name: 'MetaNFTAuctionV2', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MetaNFTAuctionV2>
getContractAt(name: 'MetaOracle', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MetaOracle>

  deployContract(name: 'ProxyAdmin', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ProxyAdmin>
deployContract(name: 'ITransparentUpgradeableProxy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITransparentUpgradeableProxy>
deployContract(name: 'TransparentUpgradeableProxy', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TransparentUpgradeableProxy>
deployContract(name: 'MetaERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MetaERC20>
deployContract(name: 'MetaNFT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MetaNFT>
deployContract(name: 'MetaNFTAuction', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MetaNFTAuction>
deployContract(name: 'MetaNFTAuctionV2', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MetaNFTAuctionV2>
deployContract(name: 'MetaOracle', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MetaOracle>

  deployContract(name: 'ProxyAdmin', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ProxyAdmin>
deployContract(name: 'ITransparentUpgradeableProxy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.ITransparentUpgradeableProxy>
deployContract(name: 'TransparentUpgradeableProxy', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.TransparentUpgradeableProxy>
deployContract(name: 'MetaERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MetaERC20>
deployContract(name: 'MetaNFT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MetaNFT>
deployContract(name: 'MetaNFTAuction', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MetaNFTAuction>
deployContract(name: 'MetaNFTAuctionV2', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MetaNFTAuctionV2>
deployContract(name: 'MetaOracle', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MetaOracle>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  