/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { Addressable } from "ethers";
import { Contract, ContractFactory, ContractTransactionResponse, Interface } from "ethers"
import type { Signer, BigNumberish, ContractDeployTransaction, ContractRunner } from "ethers"
import type { NonPayableOverrides } from "../../common.js"
  import type { MetaOracle, MetaOracleInterface } from "../../contracts/MetaOracle.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "int256",
        "name": "initialPrice",
        "type": "int256"
      }
    ],
    "stateMutability": "nonpayable",
    "type": "constructor"
  },
  {
    "inputs": [],
    "name": "getPrice",
    "outputs": [
      {
        "internalType": "int256",
        "name": "",
        "type": "int256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "latestRoundData",
    "outputs": [
      {
        "internalType": "uint80",
        "name": "roundId",
        "type": "uint80"
      },
      {
        "internalType": "int256",
        "name": "answer",
        "type": "int256"
      },
      {
        "internalType": "uint256",
        "name": "startedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "updatedAt",
        "type": "uint256"
      },
      {
        "internalType": "uint80",
        "name": "answeredInRound",
        "type": "uint80"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "int256",
        "name": "newPrice",
        "type": "int256"
      }
    ],
    "name": "setPrice",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  const _bytecode = "0x6080604052348015600e575f5ffd5b506040516102b93803806102b98339818101604052810190602e9190606b565b805f81905550506091565b5f5ffd5b5f819050919050565b604d81603d565b81146056575f5ffd5b50565b5f815190506065816046565b92915050565b5f60208284031215607d57607c6039565b5b5f6088848285016059565b91505092915050565b61021b8061009e5f395ff3fe608060405234801561000f575f5ffd5b506004361061003f575f3560e01c806398d5fdca14610043578063f7a3080614610061578063feaf968c1461007d575b5f5ffd5b61004b61009f565b60405161005891906100e6565b60405180910390f35b61007b6004803603810190610076919061012d565b6100a7565b005b6100856100b0565b604051610096959493929190610194565b60405180910390f35b5f5f54905090565b805f8190555050565b5f5f5f5f5f60015f5442426001945094509450945094509091929394565b5f819050919050565b6100e0816100ce565b82525050565b5f6020820190506100f95f8301846100d7565b92915050565b5f5ffd5b61010c816100ce565b8114610116575f5ffd5b50565b5f8135905061012781610103565b92915050565b5f60208284031215610142576101416100ff565b5b5f61014f84828501610119565b91505092915050565b5f69ffffffffffffffffffff82169050919050565b61017681610158565b82525050565b5f819050919050565b61018e8161017c565b82525050565b5f60a0820190506101a75f83018861016d565b6101b460208301876100d7565b6101c16040830186610185565b6101ce6060830185610185565b6101db608083018461016d565b969550505050505056fea2646970667358221220baf617d3ae842ec1468d34bdfbe29676da0ed4780123476b56e7adc4aa596d0764736f6c634300081c0033";

  
      type MetaOracleConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>;

      const isSuperArgs = (xs: MetaOracleConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
        xs.length > 1
    

  export class MetaOracle__factory extends ContractFactory {
    
      constructor(...args: MetaOracleConstructorParams) {
        if (isSuperArgs(args)) {
          super(...args);
        } else {
          super(_abi, _bytecode, args[0]);
        }
        
      }
    
    override getDeployTransaction(initialPrice: BigNumberish, overrides?: NonPayableOverrides & { from?: string }): Promise<ContractDeployTransaction> {
      return super.getDeployTransaction(initialPrice, overrides || {});
    };
    override deploy(initialPrice: BigNumberish, overrides?: NonPayableOverrides & { from?: string }) {
      return super.deploy(initialPrice, overrides || {}) as Promise<MetaOracle & {
        deploymentTransaction(): ContractTransactionResponse;
      }>;
    }
    override connect(runner: ContractRunner | null): MetaOracle__factory {
      return super.connect(runner) as MetaOracle__factory;
    }
    
    
    static readonly bytecode = _bytecode;
    static readonly abi = _abi;
    static createInterface(): MetaOracleInterface {
      return new Interface(_abi) as MetaOracleInterface;
    }
    
    override attach(address: string | Addressable): MetaOracle {
      return super.attach(address) as MetaOracle;
    }
  static connect(address: string, runner?: ContractRunner | null): MetaOracle {
      return new Contract(address, _abi, runner) as unknown as MetaOracle;
    }
  }

  
  