/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface MetaNFTAuctionInterface extends Interface {
    getFunction(nameOrSignature: "auctionId" | "auctions" | "bid" | "end" | "getPriceInDollar" | "getVersion" | "initialize" | "isEnded" | "setTokenOracle" | "start" | "tokenToOracle"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Bid" | "EndBid" | "Initialized" | "StartBid"): EventFragment;

    encodeFunctionData(functionFragment: 'auctionId', values?: undefined): string;
encodeFunctionData(functionFragment: 'auctions', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'bid', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'end', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getPriceInDollar', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'getVersion', values?: undefined): string;
encodeFunctionData(functionFragment: 'initialize', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'isEnded', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'setTokenOracle', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'start', values: [BigNumberish, AddressLike, BigNumberish, BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'tokenToOracle', values: [AddressLike]): string;

    decodeFunctionResult(functionFragment: 'auctionId', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'auctions', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'bid', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'end', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getPriceInDollar', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getVersion', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isEnded', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTokenOracle', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'start', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tokenToOracle', data: BytesLike): Result;
  }

  
    export namespace BidEvent {
      export type InputTuple = [sender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [sender: string, amount: bigint];
      export interface OutputObject {sender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EndBidEvent {
      export type InputTuple = [auctionId: BigNumberish];
      export type OutputTuple = [auctionId: bigint];
      export interface OutputObject {auctionId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace StartBidEvent {
      export type InputTuple = [startingBid: BigNumberish];
      export type OutputTuple = [startingBid: bigint];
      export interface OutputObject {startingBid: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface MetaNFTAuction extends BaseContract {
    
    connect(runner?: ContractRunner | null): MetaNFTAuction;
    waitForDeployment(): Promise<this>;

    interface: MetaNFTAuctionInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    auctionId: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    auctions: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, bigint, string, bigint, bigint, string, bigint, bigint, string] & {nft: string, nftId: bigint, seller: string, startingTime: bigint, highestBidder: string, startingPriceInDollar: bigint, duration: bigint, paymentToken: string, highestBid: bigint, highestBidInDollar: bigint, highestBidToken: string }],
      'view'
    >
    

    
    bid: TypedContractMethod<
      [auctionId_: BigNumberish, amount: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    end: TypedContractMethod<
      [auctionId_: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    getPriceInDollar: TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    getVersion: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [admin_: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isEnded: TypedContractMethod<
      [auctionId_: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    setTokenOracle: TypedContractMethod<
      [token: AddressLike, oracle: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    start: TypedContractMethod<
      [nftId: BigNumberish, nft: AddressLike, startingPriceInDollar: BigNumberish, duration: BigNumberish, paymentToken: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    tokenToOracle: TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'auctionId'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'auctions'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[string, bigint, string, bigint, string, bigint, bigint, string, bigint, bigint, string] & {nft: string, nftId: bigint, seller: string, startingTime: bigint, highestBidder: string, startingPriceInDollar: bigint, duration: bigint, paymentToken: string, highestBid: bigint, highestBidInDollar: bigint, highestBidToken: string }],
      'view'
    >;
getFunction(nameOrSignature: 'bid'): TypedContractMethod<
      [auctionId_: BigNumberish, amount: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'end'): TypedContractMethod<
      [auctionId_: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getPriceInDollar'): TypedContractMethod<
      [token: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getVersion'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [admin_: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isEnded'): TypedContractMethod<
      [auctionId_: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'setTokenOracle'): TypedContractMethod<
      [token: AddressLike, oracle: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'start'): TypedContractMethod<
      [nftId: BigNumberish, nft: AddressLike, startingPriceInDollar: BigNumberish, duration: BigNumberish, paymentToken: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tokenToOracle'): TypedContractMethod<
      [arg0: AddressLike, ],
      [string],
      'view'
    >;

    getEvent(key: 'Bid'): TypedContractEvent<BidEvent.InputTuple, BidEvent.OutputTuple, BidEvent.OutputObject>;
getEvent(key: 'EndBid'): TypedContractEvent<EndBidEvent.InputTuple, EndBidEvent.OutputTuple, EndBidEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'StartBid'): TypedContractEvent<StartBidEvent.InputTuple, StartBidEvent.OutputTuple, StartBidEvent.OutputObject>;

    filters: {
      
      'Bid(address,uint256)': TypedContractEvent<BidEvent.InputTuple, BidEvent.OutputTuple, BidEvent.OutputObject>;
      Bid: TypedContractEvent<BidEvent.InputTuple, BidEvent.OutputTuple, BidEvent.OutputObject>;
    

      'EndBid(uint256)': TypedContractEvent<EndBidEvent.InputTuple, EndBidEvent.OutputTuple, EndBidEvent.OutputObject>;
      EndBid: TypedContractEvent<EndBidEvent.InputTuple, EndBidEvent.OutputTuple, EndBidEvent.OutputObject>;
    

      'Initialized(uint64)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'StartBid(uint256)': TypedContractEvent<StartBidEvent.InputTuple, StartBidEvent.OutputTuple, StartBidEvent.OutputObject>;
      StartBid: TypedContractEvent<StartBidEvent.InputTuple, StartBidEvent.OutputTuple, StartBidEvent.OutputObject>;
    
    };
  }